# Who the site is for
company: "Kevin McCartney"

# Title for the page
title: "Coming soon | A landing page template"

# Meta information
subject: "A sample coming soon page"
description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec rhoncus tellus. Vestibulum ac leo ut ipsum faucibus consequat. Quisque vel."

# Verification code for Google Search Console
google_verification_token: "test"

# social media accounts. Only enter the handles, not the full URL
social:
  - twitter: "kevinmccartney"
  - google_plus: "109791538925902402449"

# the slug for your mask icon
mask_icon: "/assets/mask-icon.svg"

# defines the site's primary branding color
brand_primary: "red"

# Adds support for various meta features in the header
site_support: ["humans", "favicons", "open_graph", "schema", "twitter_card",  "mask_icon", "android_banner", "international_browsers"]

# use only the slugs for these values
background_image: "../assets/img/background.jpg"
